//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaViviendasParcial.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vivienda()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int Id_Vivienda { get; set; }
        public string DireccionCasa { get; set; }
        public Nullable<int> NumeroDeCuartos { get; set; }
        public Nullable<int> NumeroDePisos { get; set; }
        public Nullable<int> NumeroDeBanios { get; set; }
        public Nullable<decimal> Tamanio { get; set; }
        public string Accesorios { get; set; }
        public Nullable<int> Id_TipoVivienda_FK { get; set; }

        [JsonIgnore]    
        public virtual TipoVivienda TipoVivienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
